config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'products#index'

  resources :products, only: [:index, :show]

  namespace :admin do
    root 'products#index'
    resources :products, except: [:show]
    resources :vendors, except: [:show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  extend FriendlyId
  friendly_id :code_generator, use: :slugged, slug_column: :code

  validates :name, presence: true
  validates :list_price, :sell_price, numericality: { greater_than: 0, allow_nil: true }
  validates :code, uniqueness: true

  belongs_to :vendor

  private
  def code_generator
    SecureRandom.hex(10)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
      user.avatar = auth.info.image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end
end

app/models/vendor.rb
class Vendor < ApplicationRecord
  validates :title, presence: true
  acts_as_paranoid
  scope :available, -> { where(online: true) }

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_user!
  layout 'application_bd'
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  def index
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_products_path, notice: 'Product added'
    else
      render :new
    end
  end

  def edit
  end

  def upudate
  end

  def destroy
  end

  private

  def product_params
    params.require(:product).permit(:name, :vendor_id, :list_price, :sell_price)
  end
end

app/controllers/admin/vendors_controller.rb
class Admin::VendorsController < Admin::BaseController
  before_action :find_vendor, only: [:edit, :update, :destroy]
  def index
    @vendors = Vendor.all

  end

  def new
    @vendor = Vendor.new
  end

  def create
    @vendor = Vendor.new(vendor_params)
    if @vendor.save
      redirect_to admin_vendors_path, notice: '新增成功'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @vendor.update(vendor_params)
      redirect_to edit_admin_vendor_path(@vendor), notice: '資料更新成功'
    else
      render :edit
    end
  end

  def destroy
    @vendor.destroy
    redirect_to admin_vendors_path, notice: '刪除成功'
  end


  private

  def find_vendor
    @vendor = Vendor.find(params[:id])
  end

  def vendor_params
    params.require(:vendor).permit(:title, :description, :online)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  private
  def record_not_found
    render file: "#{Rails.root}/public/404.html", layout: false, status: 404
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index

  end

  def show

  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Google") if is_navigational_format?
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/products/_form.html.erb
<%= form_with(model: [:admin, product]) do |form| %>
  <div class="columns">
    <div class="column is-6">
      <div class="field">
        <%= form.label :name, '商品名稱', class: 'label' %>
        <%= form.text_field :name, class: 'input is-medium' %>
      </div>
    </div>
    <div class="column is-6">
      <div class="field">
        <%= form.label :vendor_id, '廠商', class: 'label' %>
        <div class="select is-medium is-fullwidth">
          <%= form.collection_select :vendor_id, Vendor.available, :id, :title %>
        </div>
      </div>
    </div>
  </div>

  <div class="columns">
    <div class="column">
      <div class="field">
        <%= form.label :list_price, '定價', class: 'label' %>
        <%= form.number_field :list_price, class: 'input is-medium' %>
      </div>
    </div>
    <div class="column">
      <div class="field">
        <%= form.label :sell_price, '售價', class: 'label' %>
        <%= form.number_field :sell_price, class: 'input is-medium' %>
      </div>
    </div>
  </div>

  <div class="field">
    <%= form.check_box :on_sell %>
    <%= form.label :on_sell, '是否上架？', class: 'checkbox' %>
  </div>

  <%= form.submit class: 'button is-primary is-medium' %>
<% end %>

app/views/admin/products/index.html.erb
<h1 class="title">商品例表</h1>

<%= link_to '新增商品', new_admin_product_path, class: 'button'%>

app/views/admin/products/new.html.erb
<h1 class="title">新增商品</h1>

<%= render 'form', product: @product %>

app/views/admin/vendors/_form.html.erb
<%= form_with(model: [:admin, vendor]) do |form| %>
  <div class="field">
    <%= form.label :title, '名稱', class: 'label' %>
    <%= form.text_field :title, class: 'input' %>
  </div>

  <div class="field">
    <%= form.label :description, '說明', class: 'label' %>
    <%= form.text_area :description, class: 'textarea' %>
  </div>

  <div class="field">
    <%= form.check_box :online %>
    <%= form.label :online, '正常營運中？', class: 'checkbox' %>
  </div>

  <%= form.submit class: 'button is-primary is-medium' %>
<% end %>

app/views/admin/vendors/edit.html.erb
<h1 class="title">編輯廠商</h1>
<%= render 'form', vendor: @vendor %>

app/views/admin/vendors/index.html.erb
<h1 class="title">Vendor List</h1>
<%= link_to "新增廠商", new_admin_vendor_path, class: 'button is-primary is-small' %>

<table class="table is-fullwidth">
  <thead>
    <tr>
      <th>名稱</th>
      <th>說明</th>
      <th>狀態</th>
      <th>更新時間</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @vendors.each do |vendor|%>
      <tr>
        <td><%= link_to vendor.title, edit_admin_vendor_path(vendor) %></td>
        <td><%= strip_tags(vendor.description).truncate(100) %></td>
        <td><%= vendor.online %></td>
        <td><%= vendor.updated_at %></td>
        <td>
          <%= link_to "編輯", edit_admin_vendor_path(vendor), class: 'button is-light is-small' %>
          <%= link_to "刪除", admin_vendor_path(vendor), method: :delete, data: {confirm: '確認刪除?!'}, class: 'button is-danger is-small' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/vendors/new.html.erb
<h1 class="title">新增廠商</h1>
<%= render 'form', vendor: @vendor %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyCitiesocailPractice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="turbolinks-cache-control" content="no-cache">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/flash" if notice %>
    <%= render "shared/frontend/nav_bar" %>
    <%= render "shared/frontend/top_menu" %>
    <%= yield %>
    <%= render "shared/frontend/footer" %>
  </body>
</html>

app/views/layouts/application_bd.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyCitiesocial backend</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="turbolinks-cache-control" content="no-cache">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application_bd', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/flash" if notice %>
    <%= render "shared/backend/nav_bar" %>
    <section class="container">
      <%= yield %>
    </section>
  </body>
</html>

app/views/pages/home.html.erb
<div data-controller="hello">
  <h2> Hi qwe 123</h2>
</div>

app/views/products/index.html.erb
<%= render 'shared/frontend/carousel'%>
<%= render 'shared/frontend/product_list'%>
<%= render 'shared/frontend/subscribe'%>

app/views/products/show.html.erb
<section class="container">

  <nav class="breadcrumb" aria-label="breadcrumbs">
    <ul>
      <li><a href="#">健康養生</a></li>
      <li><a href="#">輔具器材</a></li>
      <li class="is-active"><a href="#" aria-current="page">按摩伸展</a></li>
    </ul>
  </nav>

  <div class="columns">
    <div class="column is-7">
      <figure class="image">
        <%= image_pack_tag 'splash_1.jpg' %>
      </figure>

      <article class="content">
        <h4>產品特色</h4>
        <p>
          全新升級版本和一般按摩槍打擊幅度較大
          美歸馬達續航力強：6-8小時電池續航沉穩安靜
          三檔強度可調節：每分鐘可提供高達3200次震擊，適合不同受力程度
          降造更升級，實際測量最低僅36分貝，不吵躁，不影響使用心情
          升級六種按摩頭可替換：隨時依自己身體需求做調整，隨時享受各種按摩體驗
        </p>
      </article>
    </div>

    <div class="column is-5">
      <h3 class="has-text-grey-light">YOULISN</h3>
      <h2 class="title is-4">天王深層震動按摩槍-進階版</h2>
      <p class="has-text-primary is-size-4">NTD 8,811 NTD 27,600 (免運費)</p>
      <hr>
      <div class="columns">
        <div class="column is-3 is-size-4 has-text-right">
          數量
        </div>
        <div class="column is-9 field is-grouped">
          <a href="#" class="button is-white is-medium">-</a>
          <input type="number" name="quantity" class="input is-medium has-text-centered" value="1">
          <a href="#" class="button is-white is-medium">+</a>
        </div>
      </div>
      <a href="#" class="button is-primary is-medium is-fullwidth">加到購物車</a>
    </div>
  </div>
</section>

app/views/shared/_flash.html.erb
<div class="notification is-primary is-marginless">
  <button class="delete"></button>
  <i class="far fa-comment"></i> <%= notice %>
</div>

app/views/shared/backend/_nav_bar.html.erb
<nav class="navbar is-dark" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to admin_root_path, class: 'navbar-item' do %>
      <i class="fab fa-themeisle"></i>
    <% end %>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to "廠商", admin_vendors_path, class: 'navbar-item'%>
      <%= link_to "商品", admin_products_path, class: 'navbar-item'%>
    </div>
  </div>
</nav>

app/views/shared/frontend/_carousel.html.erb
<div id="carousel" class="carousel">
  <div class="carousel-item">
    <%= image_pack_tag 'splash_1.jpg' %>
  </div>
  <div class="carousel-item">
    <%= image_pack_tag 'splash_2.jpg' %>
  </div>
  <div class="carousel-item">
    <%= image_pack_tag 'splash_3.jpg' %>
  </div>
  <div class="carousel-item">
    <%= image_pack_tag 'splash_4.jpg' %>
  </div>
  <div class="carousel-item">
    <%= image_pack_tag 'splash_5.jpg' %>
  </div>
  <div class="carousel-item">
    <%= image_pack_tag 'splash_6.jpg' %>
  </div>
</div>

app/views/shared/frontend/_footer.html.erb
<footer class="footer">
  <section class="container">
    <div class="columns">
      <div class="column">
        <div class="menu">
          <p class="menu-label">關於我們</p>
          <ul class="menu-list">
            <li><a>關於</a></li>
            <li><a>隱私權保護政策</a></li>
            <li><a>服務條款</a></li>
          </ul>
        </div>
      </div>

      <div class="column">
        <div class="menu">
          <p class="menu-label">聯絡我們</p>
          <ul class="menu-list">
            <li><a>02-1234-5678</a></li>
            <li><a>業務合作洽談</a></li>
          </ul>
        </div>
      </div>

      <div class="column">
        <div class="menu">
          <p class="menu-label">自助查詢</p>
          <ul class="menu-list">
            <li><a>銀行優惠說明</a></li>
            <li><a>LINE Points 回饋說明</a></li>
            <li><a>預購商品查詢</a></li>
            <li><a>訂單出貨查詢</a></li>
            <li><a>配送進度查詢</a></li>
          </ul>
        </div>
      </div>

      <div class="column">
        <div class="menu">
          <p class="menu-label">顧客服務</p>
          <ul class="menu-list">
            <li><a>VIEWS生活誌</a></li>
            <li><a>會員回饋計畫</a></li>
            <li><a>退換貨說明</a></li>
            <li><a>客服中心</a></li>
          </ul>
        </div>
      </div>
    </div>
  </section>
</footer>

app/views/shared/frontend/_nav_bar.html.erb
<nav class="navbar has-shadow" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="/">
      <%# <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28"> %>
      <%= image_pack_tag 'logo.png' %>
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div>
      <div class="navbar-item field has-addons ">
        <div class="control">
          <input class="input" type="text" placeholder="Find a product">
        </div>
        <div class="control">
          <a class="button is-info">
            Search
          </a>
        </div>
      </div>
    </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if user_signed_in? %>
            <div class="navbar-item has-dropdown is-hoverable">
              <a class="navbar-link">
                <i class="fas fa-user"></i>&nbsp;<%= current_user.email %>
              </a>
              <div class="navbar-dropdown">
                <%= link_to "個人資料", edit_user_registration_path, class: 'navbar-item' %>
                <a class="navbar-item">
                  訂單紀錄
                </a>
                <hr class="navbar-divider">
                <%= link_to "登出", destroy_user_session_path, method: :delete, class: 'navbar-item' %>
              </div>
            </div>
          <% else %>
            <%= link_to "sign_up", new_user_registration_path, class:"button is-primary" %>
            <%= link_to "sign_in", new_user_session_path, class:"button is-light" %>
          <% end%>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/shared/frontend/_product_list.html.erb
<section class="product_list section">
  <h2 class="is-size-4 has-text-centered">限時閃購商品 － 全台獨家優惠</h2>

  <section class="container">

    <div class="columns is-multiline">
      <div class="column is-4">
        <div class="card product-item is-shadowless">
          <a href="/products/1">
            <div class="card-image">
              <figure class="image">
                <img src="https://images.unsplash.com/photo-1518791841217-8f162f1e1131?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80" alt="Placeholder image">
              </figure>
            </div>
              <div class="card-content">
                <div class="content">
                  <h4 class="is-size-6">Bermas</h4>
                  <p>30"超輕防刮大容量行李箱 完全收納</p>
                </div>
              </div>
            </a>
          </div>
      </div>

      <div class="column is-4">
        <div class="card product-item is-shadowless">
          <a href="/products/1">
            <div class="card-image">
              <figure class="image">
                <img src="https://images.unsplash.com/photo-1511044568932-338cba0ad803?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80" alt="Placeholder image">
              </figure>
            </div>
            <div class="card-content">
              <div class="content">
                <h4 class="is-size-6">美國, Honeywell</h4>
                <p>智慧抗敏空氣清淨機 兩年份耗材</p>
              </div>
            </div>
          </a>
        </div>
      </div>

      <div class="column is-4">
        <div class="card product-item is-shadowless">
          <a href="/products/1">
            <div class="card-image">
              <figure class="image">
                <img src="https://images.unsplash.com/photo-1488015795646-7e22a773d72a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80" alt="Placeholder image">
              </figure>
            </div>
            <div class="card-content">
              <div class="content">
                <h4 class="is-size-6">韓國, Xivestory</h4>
                <p>獸首無痕掛勾 居家風格更性格</p>
              </div>
            </div>
          <a>
        </div>
      </div>

      <div class="column is-4">
        <div class="card product-item is-shadowless">
          <a href="/products/1">
            <div class="card-image">
              <figure class="image">
                <img src="https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80" alt="Placeholder image">
              </figure>
            </div>
            <div class="card-content">
              <div class="content">
                <h4 class="is-size-6">日本, AUX®</h4>
                <p>大人的鐵板與實木托盤 極厚就是優秀</p>
              </div>
            </div>
          </a>
        </div>
      </div>
    </div>
  </section>
</section>

app/views/shared/frontend/_subscribe.html.erb
<section class="subscribe section has-background-light is-centered has-text-centered">
  <h3 class="has-text-centered is-size-4">訂閱電子報</h3>

  <div class="container">
    <form action="#">
      <div class="field has-addons">
        <div class="control has-icons-left is-expanded">
          <input type="email" placeholder="請輸入您的 Email 信箱" name="email" class="input is-rounded">
          <span class="icon is-small is-left">
            <i class="fas fa-envelope"></i>
          </span>
        </div>
        <div class="control">
          <input type="submit" value="訂閱電子報" class="button is-primary is-rounded">
        </div>
      </div>
    </form>
  </div>
</section>

app/views/shared/frontend/_top_menu.html.erb
<div class="tabs is-centered">
  <ul>
    <li class="is-active"><a>Pictures</a></li>
    <li><a>即時排行</a></li>
    <li><a>Top100</a></li>
    <li><a>家電</a></li>
    <li><a>科技</a></li>
    <li><a>鞋包配件</a></li>
    <li><a>運動戶外</a></li>
  </ul>
</div>